/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera, useAnimations } from '@react-three/drei'
import { useEffect } from 'react';
import * as THREE from 'three';

const japanmap = (props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/scene.glb')
  const { actions } = useAnimations(animations, group)

//   useEffect(() => {
//     if (actions) {
//         Object.values(actions).forEach((action) => {
//             action.play(); // Play all available animations
//         });
//     }
// }, [actions]);

// useEffect(() => {
//     if (actions && actions["CubeAction"] && actions["Cube.028Action"]&& actions["Cube.001Action"] && actions["Cube.1004Action"] && actions["Empty.001Action"]) {
//         const action = actions["CubeAction"];
//         action.setLoop(THREE.LoopOnce); // Play only once
//         action.clampWhenFinished = true; // Stop at the last frame
//         action.play(); // Start animation
//     }
// }, [actions]);

useEffect(() => {
    const animationNames = [
        "CubeAction",
        "Cube.028Action",
        "Cube.001Action",
        "Cube.1004Action",
        "Empty.001Action"
    ];

    if (actions) {
        const animationActions = animationNames
            .map(name => actions[name])
            .filter(action => action); // Filter out undefined actions

        animationActions.forEach(action => {
            action.setLoop(THREE.LoopOnce);
            action.clampWhenFinished = true;
            action.play();
        });
    }
}, [actions]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Pocketglb" position={[-26.203, 0, 0]}>
          <group name="Empty" />
          <directionalLight
            name="Light"
            intensity={5}
            decay={2}
            position={[37.595, 15.464, -8.598]}
            rotation={[-2.319, -0.885, 2.397]}>
            <group position={[0, 0, -1]} />
            <group position={[0, 0, -1]} />
          </directionalLight>
          <mesh
            name="Cube028"
            castShadow
            receiveShadow
            geometry={nodes.Cube028.geometry}
            material={materials['Material.002']}
            position={[27.376, 0.51, -0.192]}
            scale={0.248}
          />
          <OrthographicCamera
            name="Camera"
            makeDefault={false}
            far={1000}
            near={0.1}
            position={[27.605, 72.789, 71.519]}
            rotation={[-Math.PI / 4, 0, 0]}
          />
          <mesh
            name="Cube"
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            position={[27.406, -1.774, -0.154]}
            rotation={[0, 0.754, 0]}
          />
          <mesh
            name="Cube001"
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={nodes.Cube001.material}
            position={[29.208, -1.774, -2.392]}
            rotation={[0, 0.754, 0]}
          />
          <mesh
            name="Cube1004"
            castShadow
            receiveShadow
            geometry={nodes.Cube1004.geometry}
            material={materials['Material.004']}
            position={[29.224, 0.411, -2.386]}
            rotation={[0, 0.768, 0]}
            scale={0.325}
          />
          <group name="transform4" />
          <group name="transform2" />
          <group name="transform5" />
          <group name="transform1" />
          <group name="transform3" />
          <group name="Empty001">
            <group
              name="Cube029"
              position={[29.095, 0.156, -1.034]}
              rotation={[0, -0.171, 0]}
              scale={0.785}>
              <mesh
                name="Cube029_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube029_1.geometry}
                material={materials.BakedMaterial_01}
              />
              <mesh
                name="Cube029_2"
                castShadow
                receiveShadow
                geometry={nodes.Cube029_2.geometry}
                material={materials['BakedMaterial_01.003']}
              />
            </group>
            <group
              name="Cube338"
              position={[29.535, 0.162, -1.979]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={0.05}>
              <mesh
                name="Cube034"
                castShadow
                receiveShadow
                geometry={nodes.Cube034.geometry}
                material={materials['Material.003']}
              />
              <mesh
                name="Cube034_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube034_1.geometry}
                material={materials['Stylised Foliage']}
              />
            </group>
            <mesh
              name="Cylinder"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder.geometry}
              material={materials.MtFuji}
              position={[28.264, 0.115, -0.474]}
            />
            <mesh
              name="JP001"
              castShadow
              receiveShadow
              geometry={nodes.JP001.geometry}
              material={materials.Material}
              position={[26.874, -0.203, 0]}
            />
            <mesh
              name="JP004"
              castShadow
              receiveShadow
              geometry={nodes.JP004.geometry}
              material={materials.Dirt}
              position={[26.874, -0.203, 0]}
            />
            <group
              name="pCube3"
              position={[26.296, 0.399, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.029}>
              <mesh
                name="Mesh"
                castShadow
                receiveShadow
                geometry={nodes.Mesh.geometry}
                material={materials.BakedMaterial_01}
              />
              <mesh
                name="Mesh_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh_1.geometry}
                material={materials['BakedMaterial_01.001']}
              />
            </group>
          </group>
          <group name="Sphere" position={[27.789, 0.743, 0]} scale={[3.122, 1.774, 3.122]} />
          <group name="Volume" position={[27.422, 0, 0]} scale={[7.775, 4.242, 7.775]} />
          <mesh
            name="Plane003"
            castShadow
            receiveShadow
            geometry={nodes.Plane003.geometry}
            material={materials['Material.001']}
            position={[27.615, 0.073, -0.618]}
          />
          <mesh
            name="japancloud"
            castShadow
            receiveShadow
            geometry={nodes.japancloud.geometry}
            material={materials.japancloud}
            position={[24.011, 0.537, -4.794]}
            rotation={[Math.PI / 2, 0, -0.405]}
            scale={[3.347, 1.42, 1.42]}
          />
          <mesh
            name="japancloud001"
            castShadow
            receiveShadow
            geometry={nodes.japancloud001.geometry}
            material={materials.japancloud}
            position={[25.783, 0.688, -5.147]}
            rotation={[Math.PI / 2, 0, -0.147]}
            scale={[3.324, 0.639, 1.42]}
          />
          <mesh
            name="japancloud002"
            castShadow
            receiveShadow
            geometry={nodes.japancloud002.geometry}
            material={materials.japancloud}
            position={[23.448, 0.882, -3.737]}
            rotation={[Math.PI / 2, 0, -0.71]}
            scale={[3.324, 0.639, 2.122]}
          />
          <mesh
            name="japancloud003"
            castShadow
            receiveShadow
            geometry={nodes.japancloud003.geometry}
            material={materials.japancloud}
            position={[25.268, 0.811, -4.659]}
            rotation={[Math.PI / 2, 0, -0.285]}
            scale={[1.875, 0.361, 1.558]}
          />
          <mesh
            name="japancloud004"
            castShadow
            receiveShadow
            geometry={nodes.japancloud004.geometry}
            material={materials.japancloud}
            position={[27.208, 0.814, -4.984]}
            rotation={[Math.PI / 2, 0, -0.037]}
            scale={[2.802, 0.319, 0.962]}
          />
          <mesh
            name="japancloud005"
            castShadow
            receiveShadow
            geometry={nodes.japancloud005.geometry}
            material={materials.japancloud}
            position={[26.849, 0.377, -2.697]}
            rotation={[Math.PI / 2, 0, -0.024]}
            scale={[1.69, 0.272, 0.536]}
          />
          <mesh
            name="japancloud006"
            castShadow
            receiveShadow
            geometry={nodes.japancloud006.geometry}
            material={materials.japancloud}
            position={[24.725, 0.452, -1.618]}
            rotation={[Math.PI / 2, 0, -0.644]}
            scale={[1.71, 0.603, 0.86]}
          />
          <mesh
            name="japancloud007"
            castShadow
            receiveShadow
            geometry={nodes.japancloud007.geometry}
            material={materials.japancloud}
            position={[25.807, 0.541, -2.134]}
            rotation={[-1.576, 0.054, 0.398]}
            scale={[-2.844, -0.624, -1.117]}
          />
          <mesh
            name="japancloud008"
            castShadow
            receiveShadow
            geometry={nodes.japancloud008.geometry}
            material={materials.japancloud}
            position={[24.572, 1.321, -3.702]}
            rotation={[Math.PI / 2, 0, -0.541]}
            scale={[5.941, 3.13, 3.686]}
          />
          <mesh
            name="japancloud009"
            castShadow
            receiveShadow
            geometry={nodes.japancloud009.geometry}
            material={materials.japancloud}
            position={[29.762, 0.683, 6.299]}
            rotation={[Math.PI / 2, 0, 2.863]}
            scale={[3.669, 0.706, 4.996]}
          />
          <mesh
            name="japancloud010"
            castShadow
            receiveShadow
            geometry={nodes.japancloud010.geometry}
            material={materials.japancloud}
            position={[31.774, 0.739, 4.786]}
            rotation={[Math.PI / 2, 0, 2.3]}
            scale={[3.669, 0.706, 2.343]}
          />
          <mesh
            name="japancloud011"
            castShadow
            receiveShadow
            geometry={nodes.japancloud011.geometry}
            material={materials.japancloud}
            position={[28.14, 0.774, 6.2]}
            rotation={[Math.PI / 2, 0, 2.973]}
            scale={[3.093, 0.352, 2.602]}
          />
          <mesh
            name="japancloud012"
            castShadow
            receiveShadow
            geometry={nodes.japancloud012.geometry}
            material={materials.japancloud}
            position={[30.877, 1.382, 4.541]}
            rotation={[Math.PI / 2, 0, 2.469]}
            scale={[6.56, 3.456, 4.069]}
          />
          <mesh
            name="japancloud013"
            castShadow
            receiveShadow
            geometry={nodes.japancloud013.geometry}
            material={materials.japancloud}
            position={[25.733, 0.893, -1.876]}
            rotation={[Math.PI / 2, 0, -0.492]}
            scale={[3.45, 1.375, 2.842]}
          />
          <mesh
            name="japancloud014"
            castShadow
            receiveShadow
            geometry={nodes.japancloud014.geometry}
            material={materials.japancloud}
            position={[27.956, 0.815, 3.932]}
            rotation={[Math.PI / 2, 0, 2.821]}
            scale={[1.706, 0.804, 0.747]}
          />
          <mesh
            name="japancloud015"
            castShadow
            receiveShadow
            geometry={nodes.japancloud015.geometry}
            material={materials.japancloud}
            position={[30.817, 1.141, 2.268]}
            rotation={[Math.PI / 2, 0, 2.37]}
            scale={[1.998, 1.012, 1.253]}
          />
          <mesh
            name="japancloud016"
            castShadow
            receiveShadow
            geometry={nodes.japancloud016.geometry}
            material={materials.japancloud}
            position={[29.559, 0.792, 3.194]}
            rotation={[-1.558, -0.053, -2.602]}
            scale={[-4.169, -0.579, -1.073]}
          />
          <mesh
            name="japancloud017"
            castShadow
            receiveShadow
            geometry={nodes.japancloud017.geometry}
            material={materials.japancloud}
            position={[29.686, 1.196, 2.884]}
            rotation={[Math.PI / 2, 0, 2.509]}
            scale={[5.098, 1.28, 3.092]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/scene.glb')
export default japanmap


